var area = {
	// 根据regid查询regname
	regname: function(regid) {

	},
	// 根据id查询信息 单条记录
	areaInfo: function(regid) {
		var data = this.data;
		var result;
		var i;
		for (i = 0; i < data.length; i++) {
			if (data[i]['regid'] == regid) {
				result = data[i]
			}
		}
		return result;
	},
	//根据parid查询子数据 列表
	areaParent: function(parid) {
		var data = this.data;
		var result = [];
		var i;
		var ii = 0
		for (i = 0; i < data.length; i++) {
			if (data[i]['parid'] == parid) {
				result[ii] = data[i]
				ii++
			}
		}
		return result;
	},

	// Mysql 的地区数据
	data: [{
		"regid": "1",
		"parid": "0",
		"regname": "中国",
		"regtype": "0",
		"ageid": "0"
	}, {
		"regid": "3",
		"parid": "1",
		"regname": "安徽",
		"regtype": "1",
		"ageid": "0"
	}, {
		"regid": "3401",
		"parid": "3",
		"regname": "合肥",
		"regtype": "2",
		"ageid": "0"
	}, {
		"regid": "36",
		"parid": "3",
		"regname": "安庆",
		"regtype": "2",
		"ageid": "0"
	}, {
		"regid": "37",
		"parid": "3",
		"regname": "蚌埠",
		"regtype": "2",
		"ageid": "0"
	}, {
		"regid": "39",
		"parid": "3",
		"regname": "池州",
		"regtype": "2",
		"ageid": "0"
	}, {
		"regid": "40",
		"parid": "3",
		"regname": "滁州",
		"regtype": "2",
		"ageid": "0"
	}, {
		"regid": "41",
		"parid": "3",
		"regname": "阜阳",
		"regtype": "2",
		"ageid": "0"
	}, {
		"regid": "42",
		"parid": "3",
		"regname": "淮北",
		"regtype": "2",
		"ageid": "0"
	}, {
		"regid": "43",
		"parid": "3",
		"regname": "淮南",
		"regtype": "2",
		"ageid": "0"
	}, {
		"regid": "44",
		"parid": "3",
		"regname": "黄山",
		"regtype": "2",
		"ageid": "0"
	}, {
		"regid": "45",
		"parid": "3",
		"regname": "六安",
		"regtype": "2",
		"ageid": "0"
	}, {
		"regid": "46",
		"parid": "3",
		"regname": "马鞍山",
		"regtype": "2",
		"ageid": "0"
	}, {
		"regid": "47",
		"parid": "3",
		"regname": "宿州",
		"regtype": "2",
		"ageid": "0"
	}, {
		"regid": "48",
		"parid": "3",
		"regname": "铜陵",
		"regtype": "2",
		"ageid": "0"
	}, {
		"regid": "49",
		"parid": "3",
		"regname": "芜湖",
		"regtype": "2",
		"ageid": "0"
	}, {
		"regid": "50",
		"parid": "3",
		"regname": "宣城",
		"regtype": "2",
		"ageid": "0"
	}, {
		"regid": "51",
		"parid": "3",
		"regname": "亳州",
		"regtype": "2",
		"ageid": "0"
	}, {
		"regid": "3402",
		"parid": "3401",
		"regname": "庐阳区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "3403",
		"parid": "3401",
		"regname": "瑶海区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "3404",
		"parid": "3401",
		"regname": "蜀山区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "3405",
		"parid": "3401",
		"regname": "包河区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "3406",
		"parid": "3401",
		"regname": "长丰县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "3407",
		"parid": "3401",
		"regname": "肥东县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "3408",
		"parid": "3401",
		"regname": "肥西县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "398",
		"parid": "36",
		"regname": "迎江区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "399",
		"parid": "36",
		"regname": "大观区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "400",
		"parid": "36",
		"regname": "宜秀区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "401",
		"parid": "36",
		"regname": "桐城市",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "402",
		"parid": "36",
		"regname": "怀宁县",
		"regtype": "3",
		"ageid": "0"
	},  {
		"regid": "404",
		"parid": "36",
		"regname": "潜山县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "405",
		"parid": "36",
		"regname": "太湖县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "406",
		"parid": "36",
		"regname": "宿松县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "407",
		"parid": "36",
		"regname": "望江县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "408",
		"parid": "36",
		"regname": "岳西县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "409",
		"parid": "37",
		"regname": "龙子湖区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "410",
		"parid": "37",
		"regname": "蚌山区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "411",
		"parid": "37",
		"regname": "禹会区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "412",
		"parid": "37",
		"regname": "淮上区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "413",
		"parid": "37",
		"regname": "怀远县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "414",
		"parid": "37",
		"regname": "五河县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "415",
		"parid": "37",
		"regname": "固镇县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "416",
		"parid": "3401",
		"regname": "巢湖市",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "417",
		"parid": "3401",
		"regname": "庐江县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "418",
		"parid": "49",
		"regname": "无为县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "419",
		"parid": "46",
		"regname": "含山县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "420",
		"parid": "46",
		"regname": "和县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "421",
		"parid": "39",
		"regname": "贵池区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "422",
		"parid": "39",
		"regname": "东至县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "423",
		"parid": "39",
		"regname": "石台县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "424",
		"parid": "39",
		"regname": "青阳县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "425",
		"parid": "40",
		"regname": "琅琊区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "426",
		"parid": "40",
		"regname": "南谯区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "427",
		"parid": "40",
		"regname": "天长市",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "428",
		"parid": "40",
		"regname": "明光市",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "429",
		"parid": "40",
		"regname": "来安县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "430",
		"parid": "40",
		"regname": "全椒县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "431",
		"parid": "40",
		"regname": "定远县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "432",
		"parid": "40",
		"regname": "凤阳县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "437",
		"parid": "41",
		"regname": "颍州区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "438",
		"parid": "41",
		"regname": "颍东区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "439",
		"parid": "41",
		"regname": "颍泉区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "440",
		"parid": "41",
		"regname": "界首市",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "441",
		"parid": "41",
		"regname": "临泉县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "442",
		"parid": "41",
		"regname": "太和县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "443",
		"parid": "41",
		"regname": "阜南县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "444",
		"parid": "41",
		"regname": "颖上县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "445",
		"parid": "42",
		"regname": "相山区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "446",
		"parid": "42",
		"regname": "杜集区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "447",
		"parid": "42",
		"regname": "烈山区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "448",
		"parid": "42",
		"regname": "濉溪县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "449",
		"parid": "43",
		"regname": "田家庵区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "450",
		"parid": "43",
		"regname": "大通区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "451",
		"parid": "43",
		"regname": "谢家集区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "452",
		"parid": "43",
		"regname": "八公山区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "453",
		"parid": "43",
		"regname": "潘集区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "454",
		"parid": "43",
		"regname": "凤台县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "464",
		"parid": "43",
		"regname": "寿县",
		"regtype": "3",
		"ageid": "0"
	},
		{
		"regid": "455",
		"parid": "44",
		"regname": "屯溪区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "456",
		"parid": "44",
		"regname": "黄山区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "457",
		"parid": "44",
		"regname": "徽州区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "458",
		"parid": "44",
		"regname": "歙县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "459",
		"parid": "44",
		"regname": "休宁县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "460",
		"parid": "44",
		"regname": "黟县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "461",
		"parid": "44",
		"regname": "祁门县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "462",
		"parid": "45",
		"regname": "金安区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "463",
		"parid": "45",
		"regname": "裕安区",
		"regtype": "3",
		"ageid": "0"
	},  {
		"regid": "465",
		"parid": "45",
		"regname": "霍邱县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "466",
		"parid": "45",
		"regname": "舒城县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "467",
		"parid": "45",
		"regname": "金寨县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "468",
		"parid": "45",
		"regname": "霍山县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "469",
		"parid": "46",
		"regname": "雨山区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "470",
		"parid": "46",
		"regname": "花山区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "471",
		"parid": "46",
		"regname": "金家庄区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "472",
		"parid": "46",
		"regname": "当涂县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "473",
		"parid": "47",
		"regname": "埇桥区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "474",
		"parid": "47",
		"regname": "砀山县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "475",
		"parid": "47",
		"regname": "萧县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "476",
		"parid": "47",
		"regname": "灵璧县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "477",
		"parid": "47",
		"regname": "泗县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "478",
		"parid": "48",
		"regname": "铜官山区",
		"regtype": "3",
		"ageid": "0"
	},
	{
		"regid": "403",
		"parid": "48",
		"regname": "枞阳县",
		"regtype": "3",
		"ageid": "0"
	},{
		"regid": "479",
		"parid": "48",
		"regname": "狮子山区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "480",
		"parid": "48",
		"regname": "郊区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "481",
		"parid": "48",
		"regname": "铜陵县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "482",
		"parid": "49",
		"regname": "镜湖区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "483",
		"parid": "49",
		"regname": "弋江区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "484",
		"parid": "49",
		"regname": "鸠江区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "485",
		"parid": "49",
		"regname": "三山区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "486",
		"parid": "49",
		"regname": "芜湖县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "487",
		"parid": "49",
		"regname": "繁昌县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "488",
		"parid": "49",
		"regname": "南陵县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "489",
		"parid": "50",
		"regname": "宣州区",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "490",
		"parid": "50",
		"regname": "宁国市",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "491",
		"parid": "50",
		"regname": "郎溪县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "492",
		"parid": "50",
		"regname": "广德县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "493",
		"parid": "50",
		"regname": "泾县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "494",
		"parid": "50",
		"regname": "绩溪县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "495",
		"parid": "50",
		"regname": "旌德县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "496",
		"parid": "51",
		"regname": "涡阳县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "497",
		"parid": "51",
		"regname": "蒙城县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "498",
		"parid": "51",
		"regname": "利辛县",
		"regtype": "3",
		"ageid": "0"
	}, {
		"regid": "499",
		"parid": "51",
		"regname": "谯城区",
		"regtype": "3",
		"ageid": "0"
	},
	{
		"regid": "500",
		"parid": "45",
		"regname": "叶集区",
		"regtype": "3",
		"ageid": "0"
	}, {
			"regid": "501",
			"parid": "48",
			"regname": "义安区",
			"regtype": "3",
			"ageid": "0"
		},]
}
module.exports = area;
